#!/usr/bin/env python3
"""
NotebookLM PPT 自动去水印工具

功能：
- 自动检测并删除 PPTX 文件中的水印元素
- 支持幻灯片母版、布局、单个幻灯片
- 批量处理多个文件

使用方法：
    python remove_ppt_watermark.py input.pptx output.pptx
    python remove_ppt_watermark.py --batch ./ppt_folder/
"""

import sys
import os
from pathlib import Path
from pptx import Presentation
from pptx.enum.shapes import MSO_SHAPE_TYPE
import argparse
import re


def is_watermark_shape(shape) -> bool:
    """
    判断一个形状是否为水印元素
    
    水印特征：
    1. 包含 "NotebookLM"、"Google" 等关键词
    2. 位于幻灯片底部或角落
    3. 文字较小、颜色较淡
    4. 透明度较高
    """
    # 检查文本内容
    if hasattr(shape, "text"):
        text = shape.text.lower()
        watermark_keywords = [
            "notebooklm",
            "google",
            "made with",
            "created by",
            "generated by",
            "powered by",
            "notebook lm",
            "ai generated",
        ]
        
        for keyword in watermark_keywords:
            if keyword in text:
                return True
    
    # 检查形状名称
    shape_name = shape.name.lower()
    if "watermark" in shape_name or "notebooklm" in shape_name:
        return True
    
    # 检查形状类型（通常水印是文本框或图片）
    if hasattr(shape, "shape_type"):
        if shape.shape_type in [MSO_SHAPE_TYPE.TEXT_BOX, MSO_SHAPE_TYPE.PICTURE]:
            # 检查位置（水印通常在底部）
            if hasattr(shape, "top"):
                slide_height = 9144000  # 默认幻灯片高度（EMU 单位）
                if shape.top > slide_height * 0.85:  # 位于底部 15%
                    return True
    
    return False


def remove_watermark_from_slide(slide):
    """从单个幻灯片中删除水印"""
    removed_count = 0
    
    # 需要从后往前遍历，避免删除时索引问题
    shapes_to_remove = []
    
    for shape in slide.shapes:
        if is_watermark_shape(shape):
            shapes_to_remove.append(shape)
    
    for shape in shapes_to_remove:
        sp = shape._element
        sp.getparent().remove(sp)
        removed_count += 1
    
    return removed_count


def remove_watermark_from_master(prs):
    """从幻灯片母版中删除水印"""
    removed_count = 0
    
    # 处理幻灯片母版
    for master in prs.slide_masters:
        shapes_to_remove = []
        
        for shape in master.shapes:
            if is_watermark_shape(shape):
                shapes_to_remove.append(shape)
        
        for shape in shapes_to_remove:
            sp = shape._element
            sp.getparent().remove(sp)
            removed_count += 1
    
    # 处理幻灯片布局
    for layout in prs.slide_layouts:
        shapes_to_remove = []
        
        for shape in layout.shapes:
            if is_watermark_shape(shape):
                shapes_to_remove.append(shape)
        
        for shape in shapes_to_remove:
            sp = shape._element
            sp.getparent().remove(sp)
            removed_count += 1
    
    return removed_count


def process_pptx(input_path: str, output_path: str, verbose: bool = True) -> dict:
    """
    处理单个 PPTX 文件
    
    Args:
        input_path: 输入文件路径
        output_path: 输出文件路径
        verbose: 是否显示详细信息
    
    Returns:
        处理结果统计
    """
    try:
        # 加载 PPTX
        prs = Presentation(input_path)
        
        stats = {
            "total_slides": len(prs.slides),
            "watermarks_removed": 0,
            "master_watermarks_removed": 0,
        }
        
        if verbose:
            print(f"处理文件: {input_path}")
            print(f"总幻灯片数: {stats['total_slides']}")
        
        # 1. 删除母版和布局中的水印
        stats["master_watermarks_removed"] = remove_watermark_from_master(prs)
        
        # 2. 删除每个幻灯片中的水印
        for i, slide in enumerate(prs.slides):
            removed = remove_watermark_from_slide(slide)
            stats["watermarks_removed"] += removed
            
            if verbose and removed > 0:
                print(f"  幻灯片 {i+1}: 删除 {removed} 个水印")
        
        # 保存结果
        prs.save(output_path)
        
        if verbose:
            print(f"✅ 完成！共删除 {stats['watermarks_removed'] + stats['master_watermarks_removed']} 个水印")
            print(f"保存至: {output_path}")
        
        return stats
        
    except Exception as e:
        print(f"❌ 错误: {str(e)}", file=sys.stderr)
        return None


def batch_process(folder_path: str, output_folder: str = None, verbose: bool = True):
    """
    批量处理文件夹中的所有 PPTX 文件
    
    Args:
        folder_path: 输入文件夹路径
        output_folder: 输出文件夹路径（默认为输入文件夹/cleaned）
        verbose: 是否显示详细信息
    """
    folder = Path(folder_path)
    
    if not folder.exists():
        print(f"❌ 文件夹不存在: {folder_path}", file=sys.stderr)
        return
    
    # 创建输出文件夹
    if output_folder is None:
        output_folder = folder / "cleaned"
    else:
        output_folder = Path(output_folder)
    
    output_folder.mkdir(parents=True, exist_ok=True)
    
    # 查找所有 PPTX 文件
    pptx_files = list(folder.glob("*.pptx"))
    
    if not pptx_files:
        print(f"❌ 未找到 PPTX 文件: {folder_path}", file=sys.stderr)
        return
    
    print(f"找到 {len(pptx_files)} 个 PPTX 文件")
    print("=" * 60)
    
    total_removed = 0
    
    for pptx_file in pptx_files:
        output_path = output_folder / f"{pptx_file.stem}_cleaned{pptx_file.suffix}"
        stats = process_pptx(str(pptx_file), str(output_path), verbose)
        
        if stats:
            total_removed += stats["watermarks_removed"] + stats["master_watermarks_removed"]
        
        print()
    
    print("=" * 60)
    print(f"✅ 批量处理完成！共删除 {total_removed} 个水印")


def main():
    parser = argparse.ArgumentParser(
        description="NotebookLM PPT 自动去水印工具",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
示例:
  # 处理单个文件
  python remove_ppt_watermark.py input.pptx output.pptx

  # 批量处理文件夹
  python remove_ppt_watermark.py --batch ./ppt_folder/

  # 批量处理（指定输出文件夹）
  python remove_ppt_watermark.py --batch ./ppt_folder/ --output ./cleaned/

  # 静默模式
  python remove_ppt_watermark.py input.pptx output.pptx --quiet
        """
    )
    
    parser.add_argument("input", nargs="?", help="输入 PPTX 文件路径")
    parser.add_argument("output", nargs="?", help="输出 PPTX 文件路径")
    parser.add_argument("--batch", metavar="FOLDER", help="批量处理文件夹")
    parser.add_argument("--output", metavar="FOLDER", help="输出文件夹（批量模式）")
    parser.add_argument("--quiet", "-q", action="store_true", help="静默模式")
    
    args = parser.parse_args()
    
    verbose = not args.quiet
    
    # 批量处理模式
    if args.batch:
        batch_process(args.batch, args.output, verbose)
        return
    
    # 单文件处理模式
    if not args.input or not args.output:
        parser.print_help()
        print("\n❌ 错误: 需要指定输入和输出文件路径", file=sys.stderr)
        sys.exit(1)
    
    if not os.path.exists(args.input):
        print(f"❌ 文件不存在: {args.input}", file=sys.stderr)
        sys.exit(1)
    
    stats = process_pptx(args.input, args.output, verbose)
    
    if not stats:
        sys.exit(1)


if __name__ == "__main__":
    main()
